const products = [
    {
      product_group_id: 101,
      name: 'Pants',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Nike',
      sell_price: 50,
      sizes: ['s', 'm', 'l'],
      colors: {
        s: ['black', 'white'],
        m: ['black', 'white'],
        l: ['black'],
        xl: [],
        xxl: [],
        xxxl: [],
      },
      description: 'A pair of pants',
    },
    {
      product_group_id: 102,
      name: 'Shirt',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Adidas',
      sell_price: 30,
      sizes: ['s', 'm', 'l', 'xl'],
      colors: {
        s: ['red', 'blue'],
        m: ['red', 'blue'],
        l: ['red'],
        xl: ['blue'],
        xxl: [],
        xxxl: [],
      },
      description: 'A stylish shirt',
    },
    {
      product_group_id: 103,
      name: 'Jacket',
      image_url: 'https://via.placeholder.com/150',
      brand: 'North Face',
      sell_price: 120,
      sizes: ['m', 'l', 'xl'],
      colors: {
        s: [],
        m: ['black', 'gray'],
        l: ['black', 'gray'],
        xl: ['gray'],
        xxl: [],
        xxxl: [],
      },
      description: 'A warm jacket',
    },
    {
      product_group_id: 104,
      name: 'Sneakers',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Nike',
      sell_price: 80,
      sizes: ['s', 'm', 'l', 'xl'],
      colors: {
        s: ['white'],
        m: ['white', 'black'],
        l: ['black'],
        xl: ['black'],
        xxl: [],
        xxxl: [],
      },
      description: 'Comfortable running sneakers',
    },
    {
      product_group_id: 105,
      name: 'Jeans',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Levi\'s',
      sell_price: 60,
      sizes: ['s', 'm', 'l', 'xl'],
      colors: {
        s: ['blue'],
        m: ['blue', 'black'],
        l: ['black'],
        xl: ['blue'],
        xxl: [],
        xxxl: [],
      },
      description: 'Classic denim jeans',
    },
    {
      product_group_id: 106,
      name: 'Sweater',
      image_url: 'https://via.placeholder.com/150',
      brand: 'H&M',
      sell_price: 40,
      sizes: ['s', 'm', 'l', 'xl'],
      colors: {
        s: ['gray', 'white'],
        m: ['gray', 'white'],
        l: ['gray'],
        xl: ['white'],
        xxl: [],
        xxxl: [],
      },
      description: 'A cozy sweater',
    },
    {
      product_group_id: 107,
      name: 'Shorts',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Puma',
      sell_price: 35,
      sizes: ['s', 'm', 'l'],
      colors: {
        s: ['black', 'red'],
        m: ['black', 'red'],
        l: ['black'],
        xl: [],
        xxl: [],
        xxxl: [],
      },
      description: 'Casual sports shorts',
    },
    {
      product_group_id: 108,
      name: 'Hoodie',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Champion',
      sell_price: 55,
      sizes: ['m', 'l', 'xl', 'xxl'],
      colors: {
        s: [],
        m: ['black', 'blue'],
        l: ['black', 'blue'],
        xl: ['black'],
        xxl: ['gray'],
        xxxl: [],
      },
      description: 'A warm hoodie',
    },
    {
      product_group_id: 109,
      name: 'Sandals',
      image_url: 'https://via.placeholder.com/150',
      brand: 'Birkenstock',
      sell_price: 45,
      sizes: ['s', 'm', 'l', 'xl'],
      colors: {
        s: ['brown'],
        m: ['brown', 'black'],
        l: ['black'],
        xl: ['brown'],
        xxl: [],
        xxxl: [],
      },
      description: 'Comfortable summer sandals',
    },
    {
      product_group_id: 110,
      name: 'Cap',
      image_url: 'https://via.placeholder.com/150',
      brand: 'New Era',
      sell_price: 25,
      sizes: ['s', 'm', 'l', 'xxxl'],
      colors: {
        s: ['black', 'red'],
        m: ['black', 'red'],
        l: ['black'],
        xl: [],
        xxl: [],
        xxxl: ['red'],
      },
      description: 'A stylish cap',
    }
  ];
  
  export default products;