const mockPants = [
    {
        id: 1,
        product_id: 101, // You'll assign product IDs later
        brand: "Gap",
        color: "blue",
        size: "small",
        sku: "GAP-BLUE-S",
        sell_price: 49.99,
        stock_quantity: 25,
        reorder_point: 10,
        reorder_quantity: 50,
        reorder_price: 40.00,
        image_url: "/images/gap_blue_small.jpg",
        },
        {
        id: 2,
        product_id: 101,
        brand: "Gap",
        color: "blue",
        size: "medium",
        sku: "GAP-BLUE-M",
        sell_price: 49.99,
        stock_quantity: 15,
        reorder_point: 5,
        reorder_quantity: 50,
        reorder_price: 40.00,
        image_url: "/images/gap_blue_medium.jpg",
        },
        {
        id: 3,
        product_id: 101,
        brand: "Gap",
        color: "black",
        size: "small",
        sku: "GAP-BLACK-S",
        sell_price: 49.99,
        stock_quantity: 30,
        reorder_point: 10,
        reorder_quantity: 50,
        reorder_price: 40.00,
        image_url: "/images/gap_black_small.jpg",
        },
        {
        id: 4,
        product_id: 102,
        brand: "J Crew",
        color: "gray",
        size: "medium",
        sku: "JCREW-GRAY-M",
        sell_price: 79.50,
        stock_quantity: 20,
        reorder_point: 5,
        reorder_quantity: 30,
        reorder_price: 65.00,
        image_url: "/images/jcrew_gray_medium.jpg",
        },
        {
        id: 5,
        product_id: 102,
        brand: "J Crew",
        color: "navy",
        size: "large",
        sku: "JCREW-NAVY-L",
        sell_price: 79.50,
        stock_quantity: 10,
        reorder_point: 5,
        reorder_quantity: 30,
        reorder_price: 65.00,
        image_url: "/images/jcrew_navy_large.jpg",
        },
        {
        id: 6,
        product_id: 103,
        brand: "Levi's",
        color: "blue",
        size: "32",
        sku: "LEVIS-BLUE-32",
        sell_price: 69.99,
        stock_quantity: 40,
        reorder_point: 15,
        reorder_quantity: 60,
        reorder_price: 55.00,
        image_url: "/images/levis_blue_32.jpg",
        },
        {
        id: 7,
        product_id: 103,
        brand: "Levi's",
        color: "black",
        size: "34",
        sku: "LEVIS-BLACK-34",
        sell_price: 69.99,
        stock_quantity: 25,
        reorder_point: 10,
        reorder_quantity: 60,
        reorder_price: 55.00,
        image_url: "/images/levis_black_34.jpg",
        },
        {
        id: 8,
        product_id: 104,
        brand: "Dockers",
        color: "khaki",
        size: "medium",
        sku: "DOCKERS-KHAKI-M",
        sell_price: 59.99,
        stock_quantity: 35,
        reorder_point: 10,
        reorder_quantity: 40,
        reorder_price: 48.00,
        image_url: "/images/dockers_khaki_medium.jpg",
        },
        {
        id: 9,
        product_id: 104,
        brand: "Dockers",
        color: "gray",
        size: "large",
        sku: "DOCKERS-GRAY-L",
        sell_price: 59.99,
        stock_quantity: 18,
        reorder_point: 5,
        reorder_quantity: 40,
        reorder_price: 48.00,
        image_url: "/images/dockers_gray_large.jpg",
        },
        {
        id: 10,
        product_id: 105,
        brand: "Uniqlo",
        color: "olive",
        size: "small",
        sku: "UNIQLO-OLIVE-S",
        sell_price: 39.99,
        stock_quantity: 42,
        reorder_point: 15,
        reorder_quantity: 70,
        reorder_price: 32.00,
        image_url: "/images/uniqlo_olive_small.jpg",
        },
    ];

export default mockPants;