import ProductVariants from "../models/ProductVariants.js";

export const seedProductVariants = async () => {
  await ProductVariants.bulkCreate([
    {
      id: 1,
      product_id: 101,
      name: "Nike Running Pants",
      brand: "Nike",
      color: "red",
      size: "s",
      sku: "NIKE-RED-11",
      sell_price: 89.99,
      stock_quantity: 30,
      reorder_point: 12,
      reorder_quantity: 40,
      reorder_price: 75.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 2,
      product_id: 101,
      name: "Nike Running Pants",
      brand: "Nike",
      color: "black",
      size: "l",
      sku: "NIKE-BLK-10",
      sell_price: 89.99,
      stock_quantity: 30,
      reorder_point: 12,
      reorder_quantity: 40,
      reorder_price: 75.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 3,
      product_id: 101,
      name: "Nike Running Pants",
      brand: "Nike",
      color: "green",
      size: "xl",
      sku: "NIKE-GRN-10",
      sell_price: 89.99,
      stock_quantity: 30,
      reorder_point: 12,
      reorder_quantity: 40,
      reorder_price: 75.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 4,
      product_id: 101,
      name: "Nike Running Pants",
      brand: "Nike",
      color: "white",
      size: "m",
      sku: "NIKE-WHT-9",
      sell_price: 89.99,
      stock_quantity: 30,
      reorder_point: 12,
      reorder_quantity: 40,
      reorder_price: 75.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 5,
      product_id: 102,
      name: "Under Armour T-Shirt",
      brand: "Under Armour",
      color: "gray",
      size: "l",
      sku: "UA-GRAY-L",
      sell_price: 29.99,
      stock_quantity: 40,
      reorder_point: 15,
      reorder_quantity: 50,
      reorder_price: 22.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 6,
      product_id: 102,
      name: "Under Armour T-Shirt",
      brand: "Under Armour",
      color: "black",
      size: "m",
      sku: "UA-BLK-M",
      sell_price: 29.99,
      stock_quantity: 40,
      reorder_point: 15,
      reorder_quantity: 50,
      reorder_price: 22.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 7,
      product_id: 102,
      name: "Under Armour T-Shirt",
      brand: "Under Armour",
      color: "red",
      size: "xl",
      sku: "UA-RED-XL",
      sell_price: 29.99,
      stock_quantity: 40,
      reorder_point: 15,
      reorder_quantity: 50,
      reorder_price: 22.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 8,
      product_id: 102,
      name: "Under Armour T-Shirt",
      brand: "Under Armour",
      color: "white",
      size: "s",
      sku: "UA-WHT-S",
      sell_price: 29.99,
      stock_quantity: 40,
      reorder_point: 15,
      reorder_quantity: 50,
      reorder_price: 22.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 9,
      product_id: 102,
      name: "Under Armour T-Shirt",
      brand: "Under Armour",
      color: "red",
      size: "l",
      sku: "UA-ORG-L",
      sell_price: 29.99,
      stock_quantity: 40,
      reorder_point: 15,
      reorder_quantity: 50,
      reorder_price: 22.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 10,
      product_id: 110,
      name: "Timberland Tank Top",
      brand: "Timberland",
      color: "brown",
      size: "m",
      sku: "TIM-BROWN-11",
      sell_price: 129.99,
      stock_quantity: 12,
      reorder_point: 5,
      reorder_quantity: 20,
      reorder_price: 110.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 11,
      product_id: 111,
      name: "Hanes Socks (6-Pack)",
      brand: "Hanes",
      color: "white",
      size: "m",
      sku: "HANES-WHITE-6PK",
      sell_price: 12.99,
      stock_quantity: 50,
      reorder_point: 20,
      reorder_quantity: 60,
      reorder_price: 9.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 12,
      product_id: 112,
      name: "Lululemon Yoga Pants",
      brand: "Lululemon",
      color: "black",
      size: "s",
      sku: "LULU-BLK-S",
      sell_price: 79.99,
      stock_quantity: 16,
      reorder_point: 6,
      reorder_quantity: 25,
      reorder_price: 70.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 13,
      product_id: 112,
      name: "Lululemon Yoga Pants",
      brand: "Lululemon",
      color: "red",
      size: "xxl",
      sku: "LULU-RED-S",
      sell_price: 79.99,
      stock_quantity: 16,
      reorder_point: 6,
      reorder_quantity: 25,
      reorder_price: 70.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 14,
      product_id: 114,
      name: "Carhartt Work Pants",
      brand: "Carhartt",
      color: "brown",
      size: "xl",
      sku: "CARHARTT-BROWN-34",
      sell_price: 55.99,
      stock_quantity: 20,
      reorder_point: 8,
      reorder_quantity: 25,
      reorder_price: 45.0,
      image_url: "https://placehold.co/600x400",
    },
    {
      id: 15,
      product_id: 114,
      name: "Carhartt Work Pants",
      brand: "Carhartt",
      color: "black",
      size: "s",
      sku: "CARHARTT-BLK-36",
      sell_price: 55.99,
      stock_quantity: 20,
      reorder_point: 8,
      reorder_quantity: 25,
      reorder_price: 45.0,
      image_url: "https://placehold.co/600x400",
    },
  ]);
};
