import ProductVariants from "../models/ProductVariants.js";

export const seedProductVariants = async () => {
  await ProductVariants.bulkCreate([
    // Product Group 101
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "black", size: "xs", sku: "NIKE-BLK-2", sell_price: 89.99, image_url: "/images/nike_pants_black.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "black", size: "s", sku: "NIKE-BLK-4", sell_price: 89.99, image_url: "/images/nike_pants_black.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "black", size: "m", sku: "NIKE-BLK-6", sell_price: 89.99, image_url: "/images/nike_pants_black.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "black", size: "l", sku: "NIKE-BLK-8", sell_price: 89.99, image_url: "/images/nike_pants_black.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "black", size: "xl", sku: "NIKE-BLK-10", sell_price: 89.99, image_url: "/images/nike_pants_black.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "gray", size: "xs", sku: "NIKE-GRY-2", sell_price: 89.99, image_url: "/images/nike_pants_gray.peg" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "gray", size: "s", sku: "NIKE-GRY-4", sell_price: 89.99, image_url: "/images/nike_pants_gray.peg" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "gray", size: "m", sku: "NIKE-GRY-6", sell_price: 89.99, image_url: "/images/nike_pants_gray.peg" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "gray", size: "l", sku: "NIKE-GRY-8", sell_price: 89.99, image_url: "/images/nike_pants_gray.peg" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "gray", size: "xl", sku: "NIKE-GRY-10", sell_price: 89.99, image_url: "/images/nike_pants_gray.peg" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "navy", size: "xs", sku: "NIKE-NVY-2", sell_price: 89.99, image_url: "/images/nike_pants_navy.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "navy", size: "s", sku: "NIKE-NVY-4", sell_price: 89.99, image_url: "/images/nike_pants_navy.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "navy", size: "m", sku: "NIKE-NVY-6", sell_price: 89.99, image_url: "/images/nike_pants_navy.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "navy", size: "l", sku: "NIKE-NVY-8", sell_price: 89.99, image_url: "/images/nike_pants_navy.png" },
    { product_group_id: 101, name: "Nike AeroSwift", description: "Men's Dri-FIT ADV Running Pants", brand: "Nike", color: "navy", size: "xl", sku: "NIKE-NVY-10", sell_price: 89.99, image_url: "/images/nike_pants_navy.png" },
    
    // Product Group 102
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "academy", size: "s", sku: "UA-ADMY-S", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "academy", size: "m", sku: "UA-ADMY-M", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "academy", size: "l", sku: "UA-ADMY-L", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "academy", size: "xl", sku: "UA-ADMY-XL", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "black", size: "s", sku: "UA-BLK-S", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "black", size: "m", sku: "UA-BLK-M", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },
    { product_group_id: 102, name: "Men's UA Tech™ 2.0 Short Sleeve", description: "LOOSE, LIGHT & KEEPS YOU COOL.", brand: "Under Armour", color: "black", size: "l", sku: "UA-BLK-L", sell_price: 29.99, image_url: "/images/ua_academy_shirt.avif" },

    // Product Group 110
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "black", size: "xs", sku: "TIM-BLK-XS", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "black", size: "s", sku: "TIM-BLK-S", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "black", size: "m", sku: "TIM-BLK-M", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "black", size: "l", sku: "TIM-BLK-L", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "black", size: "xl", sku: "TIM-BLK-XL", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "white", size: "xs", sku: "TIM-WHT-XS", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "white", size: "s", sku: "TIM-WHT-S", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "white", size: "m", sku: "TIM-WHT-M", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "white", size: "l", sku: "TIM-WHT-L", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "white", size: "xl", sku: "TIM-WHT-XL", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "green", size: "xs", sku: "TIM-GRN-XS", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "green", size: "s", sku: "TIM-GRN-S", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "green", size: "m", sku: "TIM-GRN-M", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "green", size: "l", sku: "TIM-GRN-L", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "green", size: "xl", sku: "TIM-GRN-XL", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "blue", size: "xs", sku: "TIM-BLU-XS", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "blue", size: "s", sku: "TIM-BLU-S", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "blue", size: "m", sku: "TIM-BLU-M", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "blue", size: "l", sku: "TIM-BLU-L", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },
    { product_group_id: 110, name: "Timberland Tank Top", description: "A Timberland Tank Top", brand: "Timberland", color: "blue", size: "xl", sku: "TIM-BLU-XL", sell_price: 129.99, image_url: "/images/timberland_shirt.jpeg" },

    // Product Group 111
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "white", size: "s", sku: "HANES-WHITE-6PK-S", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "white", size: "m", sku: "HANES-WHITE-6PK-M", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "white", size: "l", sku: "HANES-WHITE-6PK-L", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "white", size: "xl", sku: "HANES-WHITE-6PK-XL", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "black", size: "s", sku: "HANES-BLACK-6PK-S", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "black", size: "m", sku: "HANES-BLACK-6PK-M", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "black", size: "l", sku: "HANES-BLACK-6PK-L", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "black", size: "xl", sku: "HANES-BLACK-6PK-XL", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "gray", size: "s", sku: "HANES-GRAY-6PK-S", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "gray", size: "m", sku: "HANES-GRAY-6PK-M", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "gray", size: "l", sku: "HANES-GRAY-6PK-L", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },
    { product_group_id: 111, name: "Hanes Socks (6-Pack)", description: "A pack of 6 Hanes socks", brand: "Hanes", color: "gray", size: "xl", sku: "HANES-GRAY-6PK-XL", sell_price: 12.99, image_url: "/images/hanes_socks.jpg" },

    // Product Group 112
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "black", size: "xs", sku: "LULU-BLK-XS", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "black", size: "s", sku: "LULU-BLK-S", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "black", size: "m", sku: "LULU-BLK-M", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "black", size: "l", sku: "LULU-BLK-L", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "black", size: "xl", sku: "LULU-BLK-XL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "black", size: "xxl", sku: "LULU-BLK-XXL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "red", size: "xs", sku: "LULU-RED-XS", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "red", size: "s", sku: "LULU-RED-S", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "red", size: "m", sku: "LULU-RED-M", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "red", size: "l", sku: "LULU-RED-L", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "red", size: "xl", sku: "LULU-RED-XL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "red", size: "xxl", sku: "LULU-RED-XXL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "blue", size: "xs", sku: "LULU-BLU-XS", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "blue", size: "s", sku: "LULU-BLU-S", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "blue", size: "m", sku: "LULU-BLU-M", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "blue", size: "l", sku: "LULU-BLU-L", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "blue", size: "xl", sku: "LULU-BLU-XL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "blue", size: "xxl", sku: "LULU-BLU-XXL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "gray", size: "xs", sku: "LULU-GRY-XS", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "gray", size: "s", sku: "LULU-GRY-S", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "gray", size: "m", sku: "LULU-GRY-M", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "gray", size: "l", sku: "LULU-GRY-L", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },
    { product_group_id: 112, name: "Lululemon Yoga Pants", description: "A pair of Lululemon yoga pants", brand: "Lululemon", color: "gray", size: "xl", sku: "LULU-GRY-XL", sell_price: 79.99, image_url: "/images/lululemon_pants.jpg" },

    // Product Group 114
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "black", size: "s", sku: "CARHARTT-BLK-S", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "black", size: "m", sku: "CARHARTT-BLK-M", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "black", size: "l", sku: "CARHARTT-BLK-L", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "black", size: "xl", sku: "CARHARTT-BLK-XL", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "brown", size: "s", sku: "CARHARTT-BRN-S", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "brown", size: "m", sku: "CARHARTT-BRN-M", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "brown", size: "l", sku: "CARHARTT-BRN-L", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "brown", size: "xl", sku: "CARHARTT-BRN-XL", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "navy", size: "s", sku: "CARHARTT-NAVY-S", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "navy", size: "m", sku: "CARHARTT-NAVY-M", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "navy", size: "l", sku: "CARHARTT-NAVY-L", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },
    { product_group_id: 114, name: "Carhartt Work Pants", description: "A pair of Carhartt work pants", brand: "Carhartt", color: "navy", size: "xl", sku: "CARHARTT-NAVY-XL", sell_price: 55.99, image_url: "/images/carhartt_pants.webp" },

    // Product Group 115
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "black", size: "7", sku: "ADIDAS-ULTRABOOST-BLK-7", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "black", size: "8", sku: "ADIDAS-ULTRABOOST-BLK-8", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "black", size: "9", sku: "ADIDAS-ULTRABOOST-BLK-9", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "black", size: "10", sku: "ADIDAS-ULTRABOOST-BLK-10", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "white", size: "7", sku: "ADIDAS-ULTRABOOST-WHT-7", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "white", size: "8", sku: "ADIDAS-ULTRABOOST-WHT-8", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "white", size: "9", sku: "ADIDAS-ULTRABOOST-WHT-9", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },
    { product_group_id: 115, name: "Adidas Ultraboost", description: "Adidas Ultraboost Running Shoes", brand: "Adidas", color: "white", size: "10", sku: "ADIDAS-ULTRABOOST-WHT-10", sell_price: 180.00, image_url: "/images/adidas_ultraboost.jpg" },

    // Product Group 116
    { product_group_id: 116, name: "Patagonia Refugio Backpack", description: "Patagonia Refugio 28L Backpack", brand: "Patagonia", color: "black", size: "one size", sku: "PATAGONIA-REFUGIO-BLK-ONESIZE", sell_price: 120.00, image_url: "/images/patagonia_backpack.jpg" },
    { product_group_id: 116, name: "Patagonia Refugio Backpack", description: "Patagonia Refugio 28L Backpack", brand: "Patagonia", color: "navy", size: "one size", sku: "PATAGONIA-REFUGIO-NAVY-ONESIZE", sell_price: 120.00, image_url: "/images/patagonia_backpack.jpg" },
    { product_group_id: 116, name: "Patagonia Refugio Backpack", description: "Patagonia Refugio 28L Backpack", brand: "Patagonia", color: "green", size: "one size", sku: "PATAGONIA-REFUGIO-GRN-ONESIZE", sell_price: 120.00, image_url: "/images/patagonia_backpack.jpg" },
  ]);
};
