import ProductVariants from "../models/ProductVariants.js";

export const seedProductVariants = async () => {
  await ProductVariants.bulkCreate([
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "black",
      size: "s",
      sku: "NIKE-BLK-4",
      sell_price: 89.99,
      image_url: "/images/nike_pants_black.png",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "black",
      size: "m",
      sku: "NIKE-BLK-6",
      sell_price: 89.99,
      image_url: "/images/nike_pants_black.png",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "black",
      size: "l",
      sku: "NIKE-BLK-8",
      sell_price: 89.99,
      image_url: "/images/nike_pants_black.png",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "gray",
      size: "s",
      sku: "NIKE-GRY-4",
      sell_price: 89.99,
      image_url: "/images/nike_pants_gray.peg",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "gray",
      size: "m",
      sku: "NIKE-GRY-6",
      sell_price: 89.99,
      image_url: "/images/nike_pants_gray.peg",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "gray",
      size: "l",
      sku: "NIKE-GRY-8",
      sell_price: 89.99,
      image_url: "/images/nike_pants_gray.peg",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "navy",
      size: "s",
      sku: "NIKE-NVY-4",
      sell_price: 89.99,
      image_url: "/images/nike_pants_navy.png",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "navy",
      size: "m",
      sku: "NIKE-NVY-6",
      sell_price: 89.99,
      image_url: "/images/nike_pants_navy.png",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "navy",
      size: "l",
      sku: "NIKE-NVY-8",
      sell_price: 89.99,
      image_url: "/images/nike_pants_navy.png",
    },
    {
      product_group_id: 101,
      name: "Nike AeroSwift",
      description: "Men's Dri-FIT ADV Running Pants",
      brand: "Nike",
      color: "navy",
      size: "xl",
      sku: "NIKE-NVY-10",
      sell_price: 89.99,
      image_url: "/images/nike_pants_navy.png",
    },
    {
      product_group_id: 102,
      name: "Men's UA Tech™ 2.0 Short Sleeve",
      description: "LOOSE, LIGHT & KEEPS YOU COOL. Our original go-to training gear. It's soft, ultralight, and it dries quick, so you feel cooler.",
      brand: "Under Armour",
      color: "academy",
      size: "l",
      sku: "UA-ADMY-L",
      sell_price: 29.99,
      image_url: "/images/ua_academy_shirt.avif",
    },
    {
      product_group_id: 102,
      name: "Men's UA Tech™ 2.0 Short Sleeve",
      description: "LOOSE, LIGHT & KEEPS YOU COOL. Our original go-to training gear. It's soft, ultralight, and it dries quick, so you feel cooler.",
      brand: "Under Armour",
      color: "black",
      size: "m",
      sku: "UA-BLK-M",
      sell_price: 29.99,
      image_url: "/images/ua_academy_shirt.avif",
    },
    {
      product_group_id: 102,
      name: "Men's UA Tech™ 2.0 Short Sleeve",
      description: "LOOSE, LIGHT & KEEPS YOU COOL. Our original go-to training gear. It's soft, ultralight, and it dries quick, so you feel cooler.",
      brand: "Under Armour",
      color: "red",
      size: "xl",
      sku: "UA-RED-XL",
      sell_price: 29.99,
      image_url: "/images/ua_academy_shirt.avif",
    },
    {
      product_group_id: 102,
      name: "Men's UA Tech™ 2.0 Short Sleeve",
      description: "LOOSE, LIGHT & KEEPS YOU COOL. Our original go-to training gear. It's soft, ultralight, and it dries quick, so you feel cooler.",
      brand: "Under Armour",
      color: "white",
      size: "s",
      sku: "UA-WHT-S",
      sell_price: 29.99,
      image_url: "/images/ua_academy_shirt.avif",
    },
    {
      product_group_id: 102,
      name: "Men's UA Tech™ 2.0 Short Sleeve",
      description: "LOOSE, LIGHT & KEEPS YOU COOL. Our original go-to training gear. It's soft, ultralight, and it dries quick, so you feel cooler.",
      brand: "Under Armour",
      color: "orange",
      size: "l",
      sku: "UA-ORG-L",
      sell_price: 29.99,
      image_url: "/images/ua_academy_shirt.avif",
    },
    {
      product_group_id: 110,
      name: "Timberland Tank Top",
      description: "A Timberland Tank Top",
      brand: "Timberland",
      color: "black",
      size: "m",
      sku: "TIM-BLK-11",
      sell_price: 129.99,
      image_url: "https://placehold.co/600x400",
    },
    {
      product_group_id: 111,
      name: "Hanes Socks (6-Pack)",
      description: "A pack of 6 Hanes socks",
      brand: "Hanes",
      color: "white",
      size: "m",
      sku: "HANES-WHITE-6PK",
      sell_price: 12.99,
      image_url: "https://placehold.co/600x400",
    },
    {
      product_group_id: 112,
      name: "Lululemon Yoga Pants",
      description: "A pair of Lululemon yoga pants",
      brand: "Lululemon",
      color: "black",
      size: "s",
      sku: "LULU-BLK-S",
      sell_price: 79.99,
      image_url: "https://placehold.co/600x400",
    },
    {
      product_group_id: 112,
      name: "Lululemon Yoga Pants",
      description: "A pair of Lululemon yoga pants",
      brand: "Lululemon",
      color: "red",
      size: "xxl",
      sku: "LULU-RED-S",
      sell_price: 79.99,
      image_url: "https://placehold.co/600x400",
    },
    {
      product_group_id: 114,
      name: "Carhartt Work Pants",
      description: "A pair of Carhartt work pants",
      brand: "Carhartt",
      color: "black",
      size: "xl",
      sku: "CARHARTT-BROWN-34",
      sell_price: 55.99,
      image_url: "https://placehold.co/600x400",
    },
    {
      product_group_id: 114,
      name: "Carhartt Work Pants",
      description: "A pair of Carhartt work pants",
      brand: "Carhartt",
      color: "black",
      size: "s",
      sku: "CARHARTT-BLK-36",
      sell_price: 55.99,
      image_url: "https://placehold.co/600x400",
    },
  ]);
};
